README: Use specific file & directory for file
We are getting a build error on el7:

error: Installed (but unpackaged) file(s) found:
   /usr/share/doc/ledmon/README.md
    Installed (but unpackaged) file(s) found:
   /usr/share/doc/ledmon/README.md

The %doc line works for everything else but el7, changing to
/usr/share/doc/ledmon/README.md

Signed-off-by: Tony Asleson <tasleson@redhat.com>